[build]
  command = "npm run build:netlify"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  BACKEND_URL = "https://bithead.onrender.com"
  FRONTEND_URL = "https://bithead.at"
  SOLANA_RPC_URL = "https://fragrant-icy-general.solana-mainnet.quiknode.pro/71ce468fd28dbbcf7e3a1b2e404bfacac9f60a55/"
  SOLANA_NETWORK = "mainnet-beta"

[[redirects]]
  from = "/api/*"
  to = "https://bithead.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "https://bithead.at/*"
  to = "https://www.bithead.at/:splat"
  status = 301
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization" 