[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

# Replace environment variables in config.js during build
[[plugins]]
  package = "@netlify/plugin-inject-env-vars"
  [plugins.inputs]
    files = ["public/config.js"] 